# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c45f563173d89be486be8f72ca3b5b36c62abd89388e2686b1871d46ab66418f658cd15294a46ed8e3e34f2dda2cbeab058204cbfb1921e2863582f3a21df822

test:
  secret_key_base: 726ff991c53c36fed87ba5c564e546219da484fa53e82b0b9e526bb8292028e1aa7fd29258cf8a924a8655d8f5dd551a69104a44fd1057ee7c4ae07905bc1ccb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
